app = "gamblecodez-platform"
primary_region = "iad" # or pick closest region to your audience

[build]
builder = "heroku/buildpacks:20" # or comment this if using Dockerfile

[env]
PORT = "8080"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  port = 80
  handlers = ["http"]

  [[services.ports]]
  port = 443
  handlers = ["tls", "http"]

  [[services.tcp_checks]]
  interval = "10s"
  timeout = "2s"
