app = "gamblecodez-platform"
primary_region = "iad" # or your closest Fly.io region

[build]
  builder = "heroku/buildpacks:22" # OR see step 4 if using Docker

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
