app = "gamblecodez-platform"
primary_region = "iad"

[build]  # ← only this one

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
